name: abeero
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.15
  flutter_svg:
  geolocator: ^10.0.0
  permission_handler:
  flutter_onboard: ^2.0.0
  flutter_bloc:
  dio:
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.6.2
  internet_connection_checker:
  fluttertoast:
  location: ^5.0.3
  modal_progress_hud_nsn: ^0.4.0
  firebase_auth: ^4.7.2
  firebase_storage:
  cloud_firestore: ^4.8.4




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
