name: abeero
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.7
  geolocator: ^10.0.0
  permission_handler:
  flutter_onboard: ^2.0.0
  flutter_bloc:
  dio:
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.6.2
  internet_connection_checker:
  fluttertoast:
  location: ^5.0.3
  modal_progress_hud_nsn: ^0.4.0
  firebase_auth: ^4.7.2
  firebase_storage:
  cloud_firestore: ^4.8.4
  get: ^4.6.5
  google_sign_in: ^6.1.5
  flutter_login_facebook: ^1.8.0
  flutter_facebook_auth: ^6.0.2
  dot_navigation_bar: ^1.0.2
  loading_animation_widget: ^1.2.0+4
  expandable_text: ^2.3.0
  lottie: ^2.6.0
  conditional_builder_null_safety: ^0.0.6
  sqflite: ^2.3.0
  path: ^1.8.3
  easy_stepper: ^0.8.1








dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: jannah
      fonts:
        - asset: assets/fonts/jannah.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: IconBroken
      fonts:
        - asset: assets/icons/icons.ttf

    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.OTF

